### ISSUE TITLE
Unable to Apply settings

### ISSUE THREAD

**Issue by niksingh710** [ilyazzz/LACT#48] opened 2021-12-01 05:46 UTC
`thread 'main' panicked at 'Failed to stop fan control: HWMonError', gui/src/app.rs:147:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

This error occurs when I try to apply settings.
![Screenshot_20211201_111359](https://user-images.githubusercontent.com/60490474/144178571-01f5d53f-a65f-4bb3-b3d8-891195488eb2.png)

![Screenshot_20211201_111342](https://user-images.githubusercontent.com/60490474/144178549-4bfe16d4-b468-4b06-8325-80b0f86966e4.png)

![Screenshot_20211201_111324](https://user-images.githubusercontent.com/60490474/144178528-0f54396b-9c19-4d30-a1a7-13c5df9d58e9.png)

Compiled from git. but it shows version `0.1.0 release`
```
OS: Kubuntu 21.10 x86_64 
Host: 20RV Lenovo ThinkBook 14-IML 
Kernel: 5.13.0-22-generic 
Uptime: 39 mins  
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: Plasma 5.23.3 
WM: KWin  
Terminal: konsole 
CPU: Intel i7-10510U (8) @ 1.800GHz 
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 530/535 / 620/625 Mobile 
GPU: Intel CometLake-U GT2 [UHD Graphics] 
Memory: 3215MiB / 23546MiB ```

**Comment by niksingh710** [comment] 2021-12-01 05:50
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_pstate=disable amdgpu.ppfeaturemask=0xffffffff"`

This is my Grub config-line I am also using core-ctrl.

**Comment by ilyazzz** [comment] 2021-12-01 09:27
I've pushed a fix, please update and check if the issue is gone.

**Closed** 2021-12-12 07:38 UTC
