### ISSUE TITLE
pp_dpm_* as fallback for freq

### ISSUE THREAD

**Issue by TilCreator** [ilyazzz/LACT#24] opened 2021-03-15 14:19 UTC
I have noticed that `pp_dpm_sclk` and `pp_dpm_mclk` can be used to get the shader and vram clock and also the min and max values of those.
This is very interesting for me since I'm crazy and am trying to profile an internal Picasso GPU, which doesn't have `pp_od_clk_voltage`, `freq2_input` and a bunch more.
I would like to implement those files as a fallback for `HWMon::get_gpu_freq`, `HWMon::get_mem_freq` and `GpuController::get_clocks_table`.

This is not jet a pr since I'm unsure about what the second clock speed in `GpuController::ClocksTableNew::current_gpu_clocks` is. Or should I add a new field to `GpuController::ClocksTable`?

**Comment by ilyazzz** [comment] 2021-03-15 14:30
I'm currently working on this, duplicate of #23.

In terms of code structure, I'm moving clock control out of GpuController into a separate OcController which has versions for the new clock table format (Navi+ GPUs), old (R9/Polaris/Vega) and a fallback using what you described (when either the GPU either doesn't have support or doesn't have the overclocking parameter enabled). I can make a branch with the non-ready changes if you want to see it.

**Closed by ilyazzz** 2021-03-15 14:30 UTC

**Comment by TilCreator** [comment] 2021-03-15 14:38
Ah, neat, sry for missing that ^^

**Comment by TilCreator** [comment] 2021-03-15 14:40
Thought that was something differed since it didn't mention reading the clock speeds

**Comment by TilCreator** [comment] 2021-03-15 14:45
I would love to help / test, so having the wip code would be very nice
